version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    restart: on-failure:3

  redis:
    image: redis:latest
    command: --save 20 1 --loglevel warning --requirepass M2YZTdkgLRrVkDj
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network

volumes:
  redis:
  redis-config:
  postgres:

networks:
  redis-network:
    driver: bridge
