import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Layout from "~/components/Layout";
import PostForm, { type Post } from "~/components/post/PostForm";
import { api } from "~/utils/api";

const CreatePost: NextPage = () => {
  const mutation = api.post.create.useMutation();
  const router = useRouter();

  const handleAdd = (data: Post) => {
    mutation.mutate(data);
    void router.push("/post");
  };

  return (
    <>
      <Head>
        <title>Add Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-4xl font-extrabold tracking-tight text-white ">
              Add New Post
            </h1>
            <div className="w-full rounded-xl bg-white/10 p-4 sm:w-1/3">
              <PostForm onSave={handleAdd} />
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
};

export default CreatePost;
