import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";
import Layout from "~/components/Layout";
import Pagination from "~/components/general/Pagination";
import Post from "~/components/post/Post";
import PostSkeleton from "~/components/post/PostSkeleton";
import { api } from "~/utils/api";

const MyPosts: NextPage = () => {
  const [page, setPage] = useState(1);
  const { data, status } = api.post.getAllUser.useQuery({ page });
  const { count, data: posts } = data ?? {};
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container flex flex-col items-center  gap-12 px-4 py-4 ">
            <Link
              href="/post/create"
              className="mt-20 rounded bg-green-500 px-4 py-2 text-sm font-bold text-white hover:bg-green-700 "
            >
              Add New Post
            </Link>
            {status === "error" && (
              <div className="text-2xl text-white">
                Error in fetching data...
              </div>
            )}
            <div className=" grid grid-cols-1 gap-4 text-white sm:grid-cols-3 md:gap-8">
              {status === "loading"
                ? [1, 2, 3].map((item) => <PostSkeleton key={item} />)
                : posts?.map((post) => <Post key={post.id} {...post} />)}
            </div>
            <Pagination
              currentPage={page}
              onPageChange={(current) => setPage(current)}
              totalPages={Math.ceil((count || 0) / 10)}
            />
          </div>
        </main>
      </Layout>
    </>
  );
};

export default MyPosts;
